version: '3'

services:

  database:
    image: postgres:11-alpine
    # restart: always
    expose:
      - "5432"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: daily-record-db

  adminer:
    image: adminer:latest
    # restart: always
    ports:
      - "7080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery